- include_tasks: ../../apply.yml
  vars:
    deployment: client

- include_tasks: ../../deploy.yml
  vars:
    deployment: "{{ client.application }}"

- include_tasks: ../../watch.yml
  vars:
    deployment: "{{ client.application }}"

