apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ client.application }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ client.application }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ client.application }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ client.application }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ client.application }}
          image: registry.casperinc.net/examples/algorithms/{{ client.image }}:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "500Mi"
              cpu: "500m"