apiVersion: v1
kind: Service
metadata:
  name: {{ client.application }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ client.application }}
  annotations: null
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ client.application }}